"""Fix column duplication

Revision ID: 0fc65621dd2f
Revises: 431d39aa1572
Create Date: 2024-11-25 10:46:55.318052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc65621dd2f'
down_revision = '431d39aa1572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.alter_column('mileage',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.alter_column('mileage',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
