"""Add location, availability, and mileage fields to Tractor

Revision ID: 431d39aa1572
Revises: 4ce6f28b9f9b
Create Date: 2024-11-25 10:30:30.300166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431d39aa1572'
down_revision = '4ce6f28b9f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('availability', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('availability')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
