"""Add image_url column to Tractor model

Revision ID: 4ce6f28b9f9b
Revises: 64f35c3054d6
Create Date: 2024-11-22 09:27:18.105112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce6f28b9f9b'
down_revision = '64f35c3054d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False, server_default='Default Location'))
        batch_op.add_column(sa.Column('availability', sa.Boolean, nullable=False, server_default=sa.sql.expression.false()))
        batch_op.add_column(sa.Column('mileage', sa.Float, nullable=True))

    # Remove server defaults after adding the columns
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.alter_column('location', server_default=None)
        batch_op.alter_column('availability', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
