"""Add image_url column to Tractor model

Revision ID: 4ce6f28b9f9b
Revises: 64f35c3054d6
Create Date: 2024-11-22 09:27:18.105112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce6f28b9f9b'
down_revision = '64f35c3054d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tractor', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
